package fi.raksamanageri.gui;

import fi.raksamanageri.domain.Peli;
import fi.raksamanageri.domain.Tyontekija;

/**
 * Graafinen käyttöliittymä pelaajan työntekijöiden hallintaan
 */
public class HallitseTyontekijoita extends javax.swing.JFrame {

    private Peli peli;
    private Paavalikko valikko;
    private Tyontekija valittuTyontekija;
    private int tyontekijaIndeksi;

    /**
     * Muuttujien alustus
     * 
     * @param p Peli
     * @param v Paavaliko
     */
    public HallitseTyontekijoita(Peli p, Paavalikko v) {
        this.peli = p;
        this.valikko = v;
        this.tyontekijaIndeksi = 0;
        initComponents();
        paivita();
    }

    /**
     * Päivitetään tiedot riippuen siitä onko pelaajalla työntekijöitä
     */
    public void paivita() {
        if (this.peli.getPelaaja().annaTyontekijat().isEmpty()) {
            alustaEiTyontekijoita();
        } else {
            alustaLomake(this.tyontekijaIndeksi);
        }
    }

    /**
     * Asetetaan pelaajan työntekijöiden tiedot näytölle ja samalla navigointi
     * kuntoon.
     * 
     * @param indeksi pelaajan työntekijöiden ArrayList-indeksi
     */
    private void alustaLomake(int indeksi) {
        // valitaan ensimmäinen työntekijä
        this.valittuTyontekija = this.peli.getPelaaja().annaTyontekijat().get(indeksi);

        // alustetaan tiedot edellisen mukaan
        int yhteensaTyontekijoita = this.peli.getPelaaja().annaTyontekijat().size();
        this.label_tyontekijanJarjestysNumero.setText(indeksi + 1 + "/" + yhteensaTyontekijoita);
        this.label_tyontekijaTyoteho.setText("" + this.valittuTyontekija.getTyoteho());
        this.label_tyontekijanNimi.setText(this.valittuTyontekija.getNimi());
        this.label_tyontekijanPalkka.setText("" + this.valittuTyontekija.getPalkka());
        //this.label_tyontekijanPatevyydet.setText("");
        this.button_erotaTyontekija.setEnabled(true);
        this.button_tyoMaa.setVisible(true);
        
        // asetetaan seuraavaTyontekija-nappi
        if (this.peli.getPelaaja().annaTyontekijat().size() > indeksi + 1) {
            this.button_seuraavaTyontekija.setEnabled(true);
        } else {
            this.button_seuraavaTyontekija.setEnabled(false);
        }

        // asetetaan edellinenTyontekija-nappi
        if (this.tyontekijaIndeksi > 0) {
            this.button_edellinenTyontekija.setEnabled(true);
        } else {
            this.button_edellinenTyontekija.setEnabled(false);
        }

        // laitetaan oikea teksti kansalaisuuteen
        if (this.valittuTyontekija.onkoKotimainen()) {
            this.label_tyontekijanKansalaisuus.setText("Kotimainen");
        } else {
            this.label_tyontekijanKansalaisuus.setText("Ulkomainen");
        }

        // laitetaan työntekijän työmaa oikein
        if (this.valittuTyontekija.missaToissa() != null) {
            this.button_tyoMaa.setText(this.valittuTyontekija.missaToissa().getNimi());
        } else {
            this.button_tyoMaa.setText("Ei töissä");
        }
    }

    /**
     * Asetetaan tiedot näytölle kun pelaajalla ei ole työntekijöitä
     */
    private void alustaEiTyontekijoita() {
        this.label_tyontekijanJarjestysNumero.setText("Ei työntekijöitä");
        this.label_tyontekijanJarjestysNumero.setForeground(new java.awt.Color(255, 0, 0));
        this.label_tyontekijaTyoteho.setText("");
        this.label_tyontekijanKansalaisuus.setText("");
        this.label_tyontekijanNimi.setText("");
        this.label_tyontekijanPalkka.setText("");
        this.button_edellinenTyontekija.setEnabled(false);
        this.button_seuraavaTyontekija.setEnabled(false);
        this.button_erotaTyontekija.setEnabled(false);

        this.button_tyoMaa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_seuraavaTyontekija = new javax.swing.JButton();
        button_edellinenTyontekija = new javax.swing.JButton();
        label_tyontekijanJarjestysNumero = new javax.swing.JLabel();
        label_staticNimi = new javax.swing.JLabel();
        label_tyontekijanNimi = new javax.swing.JLabel();
        label_staticKansalaisuus = new javax.swing.JLabel();
        label_tyontekijanKansalaisuus = new javax.swing.JLabel();
        label_staticTyoteho = new javax.swing.JLabel();
        label_tyontekijaTyoteho = new javax.swing.JLabel();
        label_staticPalkka = new javax.swing.JLabel();
        label_tyontekijanPalkka = new javax.swing.JLabel();
        label_staticTyopiste = new javax.swing.JLabel();
        button_valmis = new javax.swing.JButton();
        button_erotaTyontekija = new javax.swing.JButton();
        button_tyoMaa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        button_seuraavaTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_seuraavaTyontekija.setText("Seuraava");
        button_seuraavaTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_seuraavaTyontekijaActionPerformed(evt);
            }
        });

        button_edellinenTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_edellinenTyontekija.setText("Edellinen");
        button_edellinenTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edellinenTyontekijaActionPerformed(evt);
            }
        });

        label_tyontekijanJarjestysNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanJarjestysNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tyontekijanJarjestysNumero.setText("jLabel1");

        label_staticNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticNimi.setText("Nimi");

        label_tyontekijanNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanNimi.setText("jLabel1");

        label_staticKansalaisuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticKansalaisuus.setText("Kansalaisuus");

        label_tyontekijanKansalaisuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanKansalaisuus.setText("jLabel1");

        label_staticTyoteho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticTyoteho.setText("Tyoteho");

        label_tyontekijaTyoteho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijaTyoteho.setText("jLabel2");

        label_staticPalkka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticPalkka.setText("Palkka");

        label_tyontekijanPalkka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanPalkka.setText("jLabel1");

        label_staticTyopiste.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticTyopiste.setText("Työpiste");

        button_valmis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_valmis.setText("Valmis");
        button_valmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_valmisActionPerformed(evt);
            }
        });

        button_erotaTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_erotaTyontekija.setForeground(new java.awt.Color(255, 0, 0));
        button_erotaTyontekija.setText("Erota");
        button_erotaTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_erotaTyontekijaActionPerformed(evt);
            }
        });

        button_tyoMaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_tyoMaa.setText("jButton2");
        button_tyoMaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tyoMaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_edellinenTyontekija)
                                .addGap(213, 213, 213)
                                .addComponent(label_tyontekijanJarjestysNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(button_seuraavaTyontekija))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_erotaTyontekija)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_valmis))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_tyontekijanNimi)
                            .addComponent(label_staticNimi)
                            .addComponent(label_staticTyoteho)
                            .addComponent(label_tyontekijaTyoteho)
                            .addComponent(label_staticTyopiste)
                            .addComponent(button_tyoMaa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_staticKansalaisuus)
                            .addComponent(label_tyontekijanKansalaisuus)
                            .addComponent(label_staticPalkka)
                            .addComponent(label_tyontekijanPalkka))
                        .addGap(196, 196, 196)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_seuraavaTyontekija)
                    .addComponent(button_edellinenTyontekija)
                    .addComponent(label_tyontekijanJarjestysNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_staticNimi)
                    .addComponent(label_staticKansalaisuus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tyontekijanNimi)
                    .addComponent(label_tyontekijanKansalaisuus))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_staticTyoteho)
                    .addComponent(label_staticPalkka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tyontekijaTyoteho)
                    .addComponent(label_tyontekijanPalkka))
                .addGap(67, 67, 67)
                .addComponent(label_staticTyopiste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_tyoMaa)
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_erotaTyontekija)
                    .addComponent(button_valmis))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Piilota tämä ikkuna ja aseta päävalikko näkyville
     */
    private void button_valmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_valmisActionPerformed
        this.setVisible(false);
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_valmisActionPerformed

    /**
     * Poistaa pelaajalta näytöllä olevan työntekijän
     */
    private void button_erotaTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_erotaTyontekijaActionPerformed
        this.peli.getPelaaja().poistaTyontekija(this.peli.getPelaaja().annaTyontekijat().get(this.tyontekijaIndeksi));

        if (this.tyontekijaIndeksi == 0) {
            if (this.peli.getPelaaja().annaTyontekijat().size() > 0) {
                alustaLomake(this.tyontekijaIndeksi);
            } else {
                alustaEiTyontekijoita();
            }
        } else {
            alustaLomake(--this.tyontekijaIndeksi);
        }
    }//GEN-LAST:event_button_erotaTyontekijaActionPerformed

    /**
     * Asetetaan seuraavan työntekijän tiedot näytölle
     */
    private void button_seuraavaTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_seuraavaTyontekijaActionPerformed
        alustaLomake(++this.tyontekijaIndeksi);
    }//GEN-LAST:event_button_seuraavaTyontekijaActionPerformed

    /**
     * Asetetaan edellisen työntekijän tiedot näytölle
     */
    private void button_edellinenTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edellinenTyontekijaActionPerformed
        alustaLomake(--this.tyontekijaIndeksi);
    }//GEN-LAST:event_button_edellinenTyontekijaActionPerformed

    /**
     * Piilota tämä näkymä ja aseta LisaaTyontekijaTyomaalle näkyviin
     */
    private void button_tyoMaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tyoMaaActionPerformed
        // lisää työntekijä työmaalle
        LisaaTyontekijaTyomaalle l = new LisaaTyontekijaTyomaalle(peli, this, valittuTyontekija);
        this.setVisible(false);
        l.setLocation(this.getLocation().x, this.getLocation().y);
        l.setVisible(true);
    }//GEN-LAST:event_button_tyoMaaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edellinenTyontekija;
    private javax.swing.JButton button_erotaTyontekija;
    private javax.swing.JButton button_seuraavaTyontekija;
    private javax.swing.JButton button_tyoMaa;
    private javax.swing.JButton button_valmis;
    private javax.swing.JLabel label_staticKansalaisuus;
    private javax.swing.JLabel label_staticNimi;
    private javax.swing.JLabel label_staticPalkka;
    private javax.swing.JLabel label_staticTyopiste;
    private javax.swing.JLabel label_staticTyoteho;
    private javax.swing.JLabel label_tyontekijaTyoteho;
    private javax.swing.JLabel label_tyontekijanJarjestysNumero;
    private javax.swing.JLabel label_tyontekijanKansalaisuus;
    private javax.swing.JLabel label_tyontekijanNimi;
    private javax.swing.JLabel label_tyontekijanPalkka;
    // End of variables declaration//GEN-END:variables
}
