package fi.raksamanageri.gui;

import fi.raksamanageri.domain.Peli;
import fi.raksamanageri.domain.Tyomaa;
import fi.raksamanageri.domain.Tyontekija;

/**
 * Graafinen käyttöliitymä työntekijän lisäämiseen työmaalle
 */
public class LisaaTyontekijaTyomaalle extends javax.swing.JFrame {
    
    private Peli peli;
    private HallitseTyontekijoita valikko;
    private int tyomaaIndeksi;
    private Tyomaa valittuTyomaa;
    private Tyontekija tyontekija;

    /**
     * Muuttujien alustus
     * 
     * @param p Peli
     * @param v HallitseTyontekijoita (valikko)
     * @param t Tyontekija
     */
    public LisaaTyontekijaTyomaalle(Peli p, HallitseTyontekijoita v, Tyontekija t) {
        this.peli = p;
        this.valikko = v;
        this.tyomaaIndeksi = 0;
        this.tyontekija = t;
        initComponents();
        
        if (this.peli.getPelaaja().annaTyomaat().isEmpty()) {
            alustaTyhjaTyomaa();
        } else {
            alustaTyomaa(this.tyomaaIndeksi);
        }
    }
    
    /**
     * Päivitä tiedot jos työmaita ei ole
     */
    private void alustaTyhjaTyomaa() {
        this.label_tyomaanJarjestysNumero.setText("Ei työmaita");
        this.label_tyomaanJarjestysNumero.setForeground(new java.awt.Color(255, 0, 0));
        this.label_tyomaaKokonaistehokkuus.setText("");
        this.label_tyomaaValmiinaPerLaajuus.setText("");
        this.label_tyomaanNimi.setText("");
        this.label_tyomaanPalkkio.setText("");
        this.label_tyomaanTyontekijat.setText("");
        this.button_seuraavaTyomaa.setEnabled(false);
        this.button_edellinenTyomaa.setEnabled(false);
        this.button_lisaaTyontekija.setEnabled(false);
        this.label_kaytettyUlkomaista.setText("");
    }
    
    /**
     * Päivitä tiedot kun työmaita on
     * 
     * @param indeksi pelaajan työmaiden ArrayList-indeksi 
     */
    private void alustaTyomaa(int indeksi) {
        // valitaan ensimmäinen työmaa
        this.valittuTyomaa = this.peli.getPelaaja().annaTyomaat().get(indeksi);
        
        // alustetaan tiedot edellisen mukaan
        int yhteensaTyomaita = this.peli.getPelaaja().annaTyomaat().size();
        this.label_tyomaanJarjestysNumero.setText(indeksi+1 + "/" + yhteensaTyomaita);
        this.label_tyomaaKokonaistehokkuus.setText("" + this.valittuTyomaa.getKokonaisTehokkuus());
        this.label_tyomaaValmiinaPerLaajuus.setText("" + this.valittuTyomaa.getValmiina() + "/" + this.valittuTyomaa.getLaajuus());
        this.label_tyomaanNimi.setText(this.valittuTyomaa.getNimi());
        this.label_tyomaanPalkkio.setText("" + this.valittuTyomaa.getPalkkio());
        this.label_tyomaanTyontekijat.setText("" + this.valittuTyomaa.getTyontekijat().size());
        
        // asetetaan työmaan kotimaisuus
        if (this.valittuTyomaa.onkoKaytettyVainKotimaisiaTyontekijoita()) {
            this.label_kaytettyUlkomaista.setText("Ei ole");
        } else {
            this.label_kaytettyUlkomaista.setText("On");
            this.label_kaytettyUlkomaista.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        
        this.button_lisaaTyontekija.setEnabled(true);
        
        // asetetaan seuraavaTyomaa-nappi
        if (this.peli.getPelaaja().annaTyomaat().size() > indeksi+1) {
            this.button_seuraavaTyomaa.setEnabled(true);
        } else {
            this.button_seuraavaTyomaa.setEnabled(false);
        }
        
        // asetetaan edellinenTyomaa-nappi
        if (this.tyomaaIndeksi > 0) {
            this.button_edellinenTyomaa.setEnabled(true);
        } else {
            this.button_edellinenTyomaa.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_seuraavaTyomaa = new javax.swing.JButton();
        button_edellinenTyomaa = new javax.swing.JButton();
        label_tyomaanJarjestysNumero = new javax.swing.JLabel();
        label_staticNimi = new javax.swing.JLabel();
        label_tyomaanNimi = new javax.swing.JLabel();
        label_staticPalkkio = new javax.swing.JLabel();
        label_tyomaanPalkkio = new javax.swing.JLabel();
        label_staticValmiina = new javax.swing.JLabel();
        label_tyomaaValmiinaPerLaajuus = new javax.swing.JLabel();
        label_staticKokonaistehokkuus = new javax.swing.JLabel();
        label_tyomaaKokonaistehokkuus = new javax.swing.JLabel();
        label_staticKaytettyUlkomaista = new javax.swing.JLabel();
        label_kaytettyUlkomaista = new javax.swing.JLabel();
        label_staticTyontekijat = new javax.swing.JLabel();
        button_valmis = new javax.swing.JButton();
        button_lisaaTyontekija = new javax.swing.JButton();
        label_tyomaanTyontekijat = new javax.swing.JLabel();
        button_laitaVapaalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hallitse työmaitasi");
        setResizable(false);

        button_seuraavaTyomaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_seuraavaTyomaa.setText("Seuraava");
        button_seuraavaTyomaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_seuraavaTyomaaActionPerformed(evt);
            }
        });

        button_edellinenTyomaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_edellinenTyomaa.setText("Edellinen");
        button_edellinenTyomaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edellinenTyomaaActionPerformed(evt);
            }
        });

        label_tyomaanJarjestysNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanJarjestysNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tyomaanJarjestysNumero.setText("jLabel1");

        label_staticNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticNimi.setText("Nimi");

        label_tyomaanNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanNimi.setText("jLabel2");

        label_staticPalkkio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticPalkkio.setText("Palkkio");

        label_tyomaanPalkkio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanPalkkio.setText("jLabel2");

        label_staticValmiina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticValmiina.setText("Valmiina / laajuus");

        label_tyomaaValmiinaPerLaajuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaaValmiinaPerLaajuus.setText("jLabel2");

        label_staticKokonaistehokkuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticKokonaistehokkuus.setText("Työvoiman tehokkuus");

        label_tyomaaKokonaistehokkuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaaKokonaistehokkuus.setText("jLabel2");

        label_staticKaytettyUlkomaista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticKaytettyUlkomaista.setText("Käytetty ulkomaista työvoimaa");

        label_kaytettyUlkomaista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_kaytettyUlkomaista.setText("jLabel2");
        label_kaytettyUlkomaista.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        label_staticTyontekijat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticTyontekijat.setText("Työntekijöiden määrä");

        button_valmis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_valmis.setText("Valmis");
        button_valmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_valmisActionPerformed(evt);
            }
        });

        button_lisaaTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_lisaaTyontekija.setForeground(new java.awt.Color(0, 153, 0));
        button_lisaaTyontekija.setText("Lisää tälle työmaalle");
        button_lisaaTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_lisaaTyontekijaActionPerformed(evt);
            }
        });

        label_tyomaanTyontekijat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanTyontekijat.setText("jLabel1");

        button_laitaVapaalle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_laitaVapaalle.setText("Laita vapaalle");
        button_laitaVapaalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_laitaVapaalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_staticNimi)
                    .addComponent(label_tyomaanNimi)
                    .addComponent(label_staticValmiina)
                    .addComponent(label_tyomaaValmiinaPerLaajuus)
                    .addComponent(label_staticKaytettyUlkomaista)
                    .addComponent(label_kaytettyUlkomaista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_staticPalkkio)
                    .addComponent(label_tyomaanPalkkio)
                    .addComponent(label_staticKokonaistehokkuus)
                    .addComponent(label_tyomaaKokonaistehokkuus)
                    .addComponent(label_staticTyontekijat)
                    .addComponent(label_tyomaanTyontekijat))
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_edellinenTyomaa)
                        .addGap(209, 209, 209)
                        .addComponent(label_tyomaanJarjestysNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_seuraavaTyomaa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_lisaaTyontekija)
                        .addGap(148, 148, 148)
                        .addComponent(button_laitaVapaalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_valmis)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tyomaanJarjestysNumero)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_edellinenTyomaa)
                        .addComponent(button_seuraavaTyomaa)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_staticNimi)
                    .addComponent(label_staticPalkkio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tyomaanNimi)
                    .addComponent(label_tyomaanPalkkio))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_staticValmiina)
                    .addComponent(label_staticKokonaistehokkuus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tyomaaValmiinaPerLaajuus)
                    .addComponent(label_tyomaaKokonaistehokkuus))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_staticKaytettyUlkomaista)
                    .addComponent(label_staticTyontekijat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kaytettyUlkomaista)
                    .addComponent(label_tyomaanTyontekijat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_valmis)
                    .addComponent(button_lisaaTyontekija)
                    .addComponent(button_laitaVapaalle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Piilota tämä ikkuna ja aseta HallitseTyöntekijöitä näkyväksi
     */
    private void button_valmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_valmisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_valmisActionPerformed

    /**
     * Näytä seuraava työmaan tiedot
     */
    private void button_seuraavaTyomaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_seuraavaTyomaaActionPerformed
        // TODO add your handling code here:
        alustaTyomaa(++this.tyomaaIndeksi);
    }//GEN-LAST:event_button_seuraavaTyomaaActionPerformed

    /**
     * Näytä edellisen työmaan tiedot
     */
    private void button_edellinenTyomaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edellinenTyomaaActionPerformed
        // TODO add your handling code here:
        alustaTyomaa(--this.tyomaaIndeksi);
    }//GEN-LAST:event_button_edellinenTyomaaActionPerformed

    /**
     * Lisää valittu työntekijä tälle työmaalle
     */
    private void button_lisaaTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_lisaaTyontekijaActionPerformed
        // TODO add your handling code here:
        Tyomaa tm = this.peli.getPelaaja().annaTyomaat().get(this.tyomaaIndeksi);
        
        Tyomaa nytToissa = this.tyontekija.missaToissa();
        
        // jos työntekijä on jo töissä toisella työmaalla
        // poistetaan edellisestä paikasta
        if (nytToissa != null) {
            nytToissa.poistaTyontekija(this.tyontekija);
            this.tyontekija.poistaTyomaalta();
        }
        
        // lisätään työntekijä tälle työmaalle
        tm.lisaaTyontekija(this.tyontekija);
        this.tyontekija.laitaToihin(tm);
        
        this.setVisible(false);
        this.valikko.paivita();
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_lisaaTyontekijaActionPerformed

    /**
     * Poista valittu työntekijä työmaalta
     */
    private void button_laitaVapaalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_laitaVapaalleActionPerformed
        // TODO add your handling code here:
        
        Tyomaa tm = this.tyontekija.missaToissa();
        
        if (tm != null) {
            tm.poistaTyontekija(this.tyontekija);
        }
        
        this.tyontekija.poistaTyomaalta();
        
        this.setVisible(false);
        this.valikko.paivita();
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_laitaVapaalleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edellinenTyomaa;
    private javax.swing.JButton button_laitaVapaalle;
    private javax.swing.JButton button_lisaaTyontekija;
    private javax.swing.JButton button_seuraavaTyomaa;
    private javax.swing.JButton button_valmis;
    private javax.swing.JLabel label_kaytettyUlkomaista;
    private javax.swing.JLabel label_staticKaytettyUlkomaista;
    private javax.swing.JLabel label_staticKokonaistehokkuus;
    private javax.swing.JLabel label_staticNimi;
    private javax.swing.JLabel label_staticPalkkio;
    private javax.swing.JLabel label_staticTyontekijat;
    private javax.swing.JLabel label_staticValmiina;
    private javax.swing.JLabel label_tyomaaKokonaistehokkuus;
    private javax.swing.JLabel label_tyomaaValmiinaPerLaajuus;
    private javax.swing.JLabel label_tyomaanJarjestysNumero;
    private javax.swing.JLabel label_tyomaanNimi;
    private javax.swing.JLabel label_tyomaanPalkkio;
    private javax.swing.JLabel label_tyomaanTyontekijat;
    // End of variables declaration//GEN-END:variables
}
