package fi.raksamanageri.gui;

import fi.raksamanageri.domain.Peli;
import fi.raksamanageri.domain.Tyontekija;

public class PalkkaaTyontekijoita extends javax.swing.JFrame {

    private Peli peli;
    private Paavalikko valikko;
    private Tyontekija valittuTyontekija;
    private int tyontekijaIndeksi;

    public PalkkaaTyontekijoita(Peli p, Paavalikko v) {
        this.peli = p;
        this.valikko = v;
        this.tyontekijaIndeksi = 0;
        initComponents();

        // etsitään vapaat työntekijät, jos niitä on
        if (this.peli.getVapaatTyontekijat().isEmpty()) {
            alustaEiTyontekijoita();
        } else {
            alustaLomake(this.tyontekijaIndeksi);
        }
    }

    private void alustaLomake(int indeksi) {
        // valitaan ensimmäinen työntekijä
        this.valittuTyontekija = this.peli.getVapaatTyontekijat().get(indeksi);
        
        // alustetaan tiedot edellisen mukaan
        int yhteensaTyontekijoita = this.peli.getVapaatTyontekijat().size();
        this.label_tyontekijanJarjestysNumero.setText(indeksi+1 + "/" + yhteensaTyontekijoita);
        this.label_tyontekijaTyoteho.setText("" + this.valittuTyontekija.getTyoteho());
        this.label_tyontekijanNimi.setText(this.valittuTyontekija.getNimi());
        this.label_tyontekijanPalkka.setText("" + this.valittuTyontekija.getPalkka());
        this.button_palkkaaTyontekija.setEnabled(true);
        
        // asetetaan seuraavaTyontekija-nappi
        if (this.peli.getVapaatTyontekijat().size() > indeksi+1) {
            this.button_seuraavaTyontekija.setEnabled(true);
        } else {
            this.button_seuraavaTyontekija.setEnabled(false);
        }
        
        // asetetaan edellinenTyontekija-nappi
        if (this.tyontekijaIndeksi > 0) {
            this.button_edellinenTyontekija.setEnabled(true);
        } else {
            this.button_edellinenTyontekija.setEnabled(false);
        }
        
        // laitetaan oikea teksti kansalaisuuteen
        if (this.valittuTyontekija.onkoKotimainen()) {
            this.label_tyontekijanKansalaisuus.setText("Kotimainen");
        } else {
            this.label_tyontekijanKansalaisuus.setText("Ulkomainen");
        }
    }

    private void alustaEiTyontekijoita() {
        this.label_tyontekijanJarjestysNumero.setText("Ei työntekijöitä saatavilla");
        this.label_tyontekijanJarjestysNumero.setForeground(new java.awt.Color(255, 0, 0));
        this.label_tyontekijaTyoteho.setText("");
        this.label_tyontekijanKansalaisuus.setText("");
        this.label_tyontekijanNimi.setText("");
        this.label_tyontekijanPalkka.setText("");
        this.button_edellinenTyontekija.setEnabled(false);
        this.button_seuraavaTyontekija.setEnabled(false);
        this.button_palkkaaTyontekija.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_seuraavaTyontekija = new javax.swing.JButton();
        button_edellinenTyontekija = new javax.swing.JButton();
        label_tyontekijanJarjestysNumero = new javax.swing.JLabel();
        label_staticNimi = new javax.swing.JLabel();
        label_tyontekijanNimi = new javax.swing.JLabel();
        label_staticKansalaisuus = new javax.swing.JLabel();
        label_tyontekijanKansalaisuus = new javax.swing.JLabel();
        label_staticTyoteho = new javax.swing.JLabel();
        label_tyontekijaTyoteho = new javax.swing.JLabel();
        label_staticPalkka = new javax.swing.JLabel();
        label_tyontekijanPalkka = new javax.swing.JLabel();
        button_valmis = new javax.swing.JButton();
        button_palkkaaTyontekija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        button_seuraavaTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_seuraavaTyontekija.setText("Seuraava");
        button_seuraavaTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_seuraavaTyontekijaActionPerformed(evt);
            }
        });

        button_edellinenTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_edellinenTyontekija.setText("Edellinen");
        button_edellinenTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edellinenTyontekijaActionPerformed(evt);
            }
        });

        label_tyontekijanJarjestysNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanJarjestysNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tyontekijanJarjestysNumero.setText("jLabel1");

        label_staticNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticNimi.setText("Nimi");

        label_tyontekijanNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanNimi.setText("jLabel1");

        label_staticKansalaisuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticKansalaisuus.setText("Kansalaisuus");

        label_tyontekijanKansalaisuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanKansalaisuus.setText("jLabel1");

        label_staticTyoteho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticTyoteho.setText("Tyoteho");

        label_tyontekijaTyoteho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijaTyoteho.setText("jLabel2");

        label_staticPalkka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticPalkka.setText("Palkka");

        label_tyontekijanPalkka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyontekijanPalkka.setText("jLabel1");

        button_valmis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_valmis.setText("Valmis");
        button_valmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_valmisActionPerformed(evt);
            }
        });

        button_palkkaaTyontekija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_palkkaaTyontekija.setForeground(new java.awt.Color(51, 153, 0));
        button_palkkaaTyontekija.setText("Palkkaa");
        button_palkkaaTyontekija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_palkkaaTyontekijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_edellinenTyontekija)
                                .addGap(213, 213, 213)
                                .addComponent(label_tyontekijanJarjestysNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(button_seuraavaTyontekija))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_palkkaaTyontekija)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_valmis))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_tyontekijanNimi)
                            .addComponent(label_staticNimi)
                            .addComponent(label_staticTyoteho)
                            .addComponent(label_tyontekijaTyoteho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_staticKansalaisuus)
                            .addComponent(label_tyontekijanKansalaisuus)
                            .addComponent(label_staticPalkka)
                            .addComponent(label_tyontekijanPalkka))
                        .addGap(198, 198, 198)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_seuraavaTyontekija)
                    .addComponent(button_edellinenTyontekija)
                    .addComponent(label_tyontekijanJarjestysNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_staticNimi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tyontekijanNimi)
                        .addGap(74, 74, 74)
                        .addComponent(label_staticTyoteho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tyontekijaTyoteho))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_staticKansalaisuus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tyontekijanKansalaisuus)
                        .addGap(74, 74, 74)
                        .addComponent(label_staticPalkka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tyontekijanPalkka)))
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_palkkaaTyontekija)
                    .addComponent(button_valmis))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_valmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_valmisActionPerformed
        this.setVisible(false);
        this.valikko.updatePaavalikko();
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_valmisActionPerformed

    private void button_seuraavaTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_seuraavaTyontekijaActionPerformed
        alustaLomake(++this.tyontekijaIndeksi);
    }//GEN-LAST:event_button_seuraavaTyontekijaActionPerformed

    private void button_edellinenTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edellinenTyontekijaActionPerformed
        alustaLomake(--this.tyontekijaIndeksi);
    }//GEN-LAST:event_button_edellinenTyontekijaActionPerformed

    private void button_palkkaaTyontekijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_palkkaaTyontekijaActionPerformed
        
        Tyontekija te = this.peli.getVapaatTyontekijat().get(this.tyontekijaIndeksi);
        
        // lisätään työntekijä pelaajalle
        this.peli.getPelaaja().lisaaTyontekija(te);
        
        // poistetaan työntekijä rekrytoitavien joukosta
        this.peli.poistaUusiTyontekija(te);

        if (this.tyontekijaIndeksi == 0) {
            if (this.peli.getVapaatTyontekijat().size() > 0) {
                alustaLomake(this.tyontekijaIndeksi);
            } else {
                alustaEiTyontekijoita();
            }
        } else {
            alustaLomake(--this.tyontekijaIndeksi);
        }
    }//GEN-LAST:event_button_palkkaaTyontekijaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HallitseTyontekijoita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HallitseTyontekijoita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HallitseTyontekijoita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HallitseTyontekijoita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HallitseTyontekijoita().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edellinenTyontekija;
    private javax.swing.JButton button_palkkaaTyontekija;
    private javax.swing.JButton button_seuraavaTyontekija;
    private javax.swing.JButton button_valmis;
    private javax.swing.JLabel label_staticKansalaisuus;
    private javax.swing.JLabel label_staticNimi;
    private javax.swing.JLabel label_staticPalkka;
    private javax.swing.JLabel label_staticTyoteho;
    private javax.swing.JLabel label_tyontekijaTyoteho;
    private javax.swing.JLabel label_tyontekijanJarjestysNumero;
    private javax.swing.JLabel label_tyontekijanKansalaisuus;
    private javax.swing.JLabel label_tyontekijanNimi;
    private javax.swing.JLabel label_tyontekijanPalkka;
    // End of variables declaration//GEN-END:variables
}
