package fi.raksamanageri.gui;

import fi.raksamanageri.domain.Peli;
import fi.raksamanageri.domain.Tyomaa;

/**
 * Graafinen käyttöliittymä uuden työmaan valitsemiseksi
 */

public class ValitseUusiTyomaa extends javax.swing.JFrame {
    
    private Peli peli;
    private Paavalikko valikko;
    private int tyomaaIndeksi;
    private Tyomaa valittuTyomaa;

    /**
     * Muuttujien alustaminen
     * 
     * @param p Peli
     * @param v Päävalikko
     */
    public ValitseUusiTyomaa(Peli p, Paavalikko v) {
        this.peli = p;
        this.valikko = v;
        this.tyomaaIndeksi = 0;
        initComponents();
        
        if (this.peli.getTyomaat().isEmpty()) {
            alustaTyhjaTyomaa();
        } else {
            alustaTyomaa(this.tyomaaIndeksi);
        }
    }
    
    /**
     * Alustaa näytön tiedot kun työmaita ei ole saatavilla
     */
    private void alustaTyhjaTyomaa() {
        this.label_tyomaanJarjestysNumero.setText("Ei uusia työmaita...");
        this.label_tyomaanJarjestysNumero.setForeground(new java.awt.Color(255, 0, 0));
        this.label_tyomaaLaajuus.setText("");
        this.label_tyomaanNimi.setText("");
        this.label_tyomaanPalkkio.setText("");
        this.button_seuraavaTyomaa.setEnabled(false);
        this.button_edellinenTyomaa.setEnabled(false);
        this.button_valitseTyomaa.setEnabled(false);
    }
    
    /**
     * Alustaa työmaan tiedot näytölle
     * 
     * @param indeksi Pelin vaipaiden työmaiden ArrayList-indeksi 
     */
    private void alustaTyomaa(int indeksi) {
        // valitaan ensimmäinen työmaa
        this.valittuTyomaa = this.peli.getTyomaat().get(indeksi);
        
        // alustetaan tiedot edellisen mukaan
        int yhteensaTyomaita = this.peli.getTyomaat().size();
        this.label_tyomaanJarjestysNumero.setText(indeksi+1 + "/" + yhteensaTyomaita);
        this.label_tyomaaLaajuus.setText("" + this.valittuTyomaa.getLaajuus());
        this.label_tyomaanNimi.setText(this.valittuTyomaa.getNimi());
        this.label_tyomaanPalkkio.setText("" + this.valittuTyomaa.getPalkkio());
        
        this.button_valitseTyomaa.setEnabled(true);
        
        // asetetaan seuraavaTyomaa-nappi
        if (this.peli.getTyomaat().size() > indeksi+1) {
            this.button_seuraavaTyomaa.setEnabled(true);
        } else {
            this.button_seuraavaTyomaa.setEnabled(false);
        }
        
        // asetetaan edellinenTyomaa-nappi
        if (this.tyomaaIndeksi > 0) {
            this.button_edellinenTyomaa.setEnabled(true);
        } else {
            this.button_edellinenTyomaa.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_seuraavaTyomaa = new javax.swing.JButton();
        button_edellinenTyomaa = new javax.swing.JButton();
        label_tyomaanJarjestysNumero = new javax.swing.JLabel();
        label_staticNimi = new javax.swing.JLabel();
        label_tyomaanNimi = new javax.swing.JLabel();
        label_staticPalkkio = new javax.swing.JLabel();
        label_tyomaanPalkkio = new javax.swing.JLabel();
        label_staticLaajuus = new javax.swing.JLabel();
        label_tyomaaLaajuus = new javax.swing.JLabel();
        button_valmis = new javax.swing.JButton();
        button_valitseTyomaa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hallitse työmaitasi");
        setResizable(false);

        button_seuraavaTyomaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_seuraavaTyomaa.setText("Seuraava");
        button_seuraavaTyomaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_seuraavaTyomaaActionPerformed(evt);
            }
        });

        button_edellinenTyomaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_edellinenTyomaa.setText("Edellinen");
        button_edellinenTyomaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edellinenTyomaaActionPerformed(evt);
            }
        });

        label_tyomaanJarjestysNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanJarjestysNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tyomaanJarjestysNumero.setText("jLabel1");

        label_staticNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticNimi.setText("Nimi");

        label_tyomaanNimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanNimi.setText("jLabel2");

        label_staticPalkkio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticPalkkio.setText("Palkkio");

        label_tyomaanPalkkio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaanPalkkio.setText("jLabel2");

        label_staticLaajuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_staticLaajuus.setText("Laajuus");

        label_tyomaaLaajuus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_tyomaaLaajuus.setText("jLabel2");

        button_valmis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_valmis.setText("Valmis");
        button_valmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_valmisActionPerformed(evt);
            }
        });

        button_valitseTyomaa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_valitseTyomaa.setForeground(new java.awt.Color(51, 153, 0));
        button_valitseTyomaa.setText("Valitse työmaa");
        button_valitseTyomaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_valitseTyomaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_edellinenTyomaa)
                        .addGap(209, 209, 209)
                        .addComponent(label_tyomaanJarjestysNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(button_seuraavaTyomaa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_valitseTyomaa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_valmis)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_staticPalkkio)
                    .addComponent(label_tyomaanPalkkio)
                    .addComponent(label_staticNimi)
                    .addComponent(label_tyomaanNimi)
                    .addComponent(label_staticLaajuus)
                    .addComponent(label_tyomaaLaajuus))
                .addGap(368, 368, 368))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tyomaanJarjestysNumero)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_edellinenTyomaa)
                        .addComponent(button_seuraavaTyomaa)))
                .addGap(83, 83, 83)
                .addComponent(label_staticNimi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tyomaanNimi)
                .addGap(76, 76, 76)
                .addComponent(label_staticPalkkio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tyomaanPalkkio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(label_staticLaajuus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tyomaaLaajuus)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_valmis)
                    .addComponent(button_valitseTyomaa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Piilota tämä ikkuna ja aseta Päävalikko näkyville
     */
    private void button_valmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_valmisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.valikko.updatePaavalikko();
        this.valikko.setLocation(this.getLocation().x, this.getLocation().y);
        this.valikko.setVisible(true);
    }//GEN-LAST:event_button_valmisActionPerformed

    /**
     * Näytä pelin seuraavan vapaan työmaan tiedot
     */
    private void button_seuraavaTyomaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_seuraavaTyomaaActionPerformed
        // TODO add your handling code here:
        alustaTyomaa(++this.tyomaaIndeksi);
    }//GEN-LAST:event_button_seuraavaTyomaaActionPerformed

    /**
     * Näytä pelin edellisen vapaan työmaan tiedot
     */
    private void button_edellinenTyomaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edellinenTyomaaActionPerformed
        // TODO add your handling code here:
        alustaTyomaa(--this.tyomaaIndeksi);
    }//GEN-LAST:event_button_edellinenTyomaaActionPerformed

    /**
     * Lisää näkyvillä oleva työmaa pelaajalle
     */
    private void button_valitseTyomaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_valitseTyomaaActionPerformed
        // TODO add your handling code here:
        Tyomaa tm = this.peli.getTyomaat().get(this.tyomaaIndeksi);
        
        // lisää työmaa pelaajalle
        this.peli.getPelaaja().lisääTyomaa(tm);
        
        // poista työmaa vapaiden listalta
        this.peli.poistaUusiTyomaa(tm);
        
        if (this.tyomaaIndeksi == 0) {
            if (this.peli.getTyomaat().size() > 0) {
                alustaTyomaa(this.tyomaaIndeksi);
            } else {
                alustaTyhjaTyomaa();
            }
        } else {
            alustaTyomaa(--this.tyomaaIndeksi);
        }
    }//GEN-LAST:event_button_valitseTyomaaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edellinenTyomaa;
    private javax.swing.JButton button_seuraavaTyomaa;
    private javax.swing.JButton button_valitseTyomaa;
    private javax.swing.JButton button_valmis;
    private javax.swing.JLabel label_staticLaajuus;
    private javax.swing.JLabel label_staticNimi;
    private javax.swing.JLabel label_staticPalkkio;
    private javax.swing.JLabel label_tyomaaLaajuus;
    private javax.swing.JLabel label_tyomaanJarjestysNumero;
    private javax.swing.JLabel label_tyomaanNimi;
    private javax.swing.JLabel label_tyomaanPalkkio;
    // End of variables declaration//GEN-END:variables
}
